services:
  lab:
    container_name: saopaulo
    build: .
    volumes:
      - .:/home/jovyan/work
    ports:
      - '8888:8888'
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      GRANT_SUDO: 'yes'
    user: 'root'
