version: '3'
services:
  lab:
    container_name: portalrecerca
    image: yufernando/jupyterlab:snakemake
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work/
    ports:
      - '8888:8888'
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      GRANT_SUDO: 'yes'
    user: 'root'
